name: PandoDungeons
version: 4.7
main: pandodungeons.pandodungeons.PandoDungeons
api-version: 1.21
authors: [Alepando]
website: mapachos.com

commands:
  dungeons:
    description: Comando principal de Dungeons.
    usage: /<command> [play|leave|stats|stadistics|boss|statsbook|companion|companionmenu]

  redondel:
    description: Comando para redondel
    usage: /<command> play

  party:
    description: Comando para crear una party
    usage: /<command> [create|invite|delete]

  texturas:
    description: Aplica last texturas del servidor
    usage: /<command>

  gachatoken:
    description: Para dar tokens de gacha
    usage: /<command>

  stats:
    description: Para ver las stats de clase
    usage: /<command>

  bet:
    description: Comando para apostar
    usage: /<command>

permissions:
  pandodungeons.pandaMount:
    description: Permiso para montar y controlar un panda.
    default: op
  pandodungeons.end:
    description: Permiso Staff para ir al end.
    default: op
