name: PandoDungeons
version: 1.0
main: pandodungeons.pandodungeons.PandoDungeons
api-version: 1.21
authors: [Alepando]
website: mapachos.com

commands:
  dungeons:
    description: Comando principal de Dungeons.
    usage: /<command> [play|leave|stats|stadistics|boss|statsbook|companion|companionmenu]

  redondel:
    description: Comando para redondel
    usage: /<command> play

  party:
    description: Comando para crear una party
    usage: /<command> [create|invite|delete]

permissions:
  pandodungeons.pandaMount:
    description: Permiso para montar y controlar un panda.
    default: op
